#ifndef CPP2_S21_CONTAINERS_SRC_S21_CONTAINERSPLUS_H_
#define CPP2_S21_CONTAINERS_SRC_S21_CONTAINERSPLUS_H_

#include "s21_containersplus/array/s21_array.h"

#endif  // CPP2_S21_CONTAINERS_SRC_S21_CONTAINERSPLUS_H_